# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Setup Poetry
      uses: Gr1N/setup-poetry@v8    
    - name: Poetry Install
      run: | 
        poetry install
    - name: Lint with flake8
      run: |
        poetry run task lint_flake8
    - name: Lint with black
      run: |
        poetry run task lint_black
    - name: Lint with mypy
      run: |
        poetry run task lint_mypy
    - name: Run unittests with pytest
      run: |
        poetry run task test
        
